name: CI

on:
  push:

jobs:
  build:
    name: Build (${{ matrix.os }}, Swift ${{ matrix.swift-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift-version: ["5.8"]
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}
      - uses: actions/checkout@v3
      - name: Build
        run: make build

  test:
    name: Test (${{ matrix.os }}, Swift ${{ matrix.swift-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # masos-latest is disabled due to unknown error
        # i.e. https://github.com/andooown/swift-atproto/actions/runs/5891991845/job/15980295242
        os: [ubuntu-latest]
        swift-version: ["5.8"]
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}
      - uses: actions/checkout@v3
      - name: Test
        run: make test
