name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build (${{ matrix.os }}, Swift ${{ matrix.swift-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]
        swift-version: ["5.9"]
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}
      - uses: actions/checkout@v3
      - name: Build
        run: make build

  test:
    name: Test (${{ matrix.os }}, Swift ${{ matrix.swift-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # masos-latest is disabled due to unknown error
        # i.e. https://github.com/andooown/swift-atproto/actions/runs/5891991845/job/15980295242
        os: [ubuntu-latest]
        swift-version: ["5.9"]
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}
      - uses: actions/checkout@v3
      - name: Test
        run: make test
  
  test-on-ios-beta:
    name: Test on iOS Beta
    runs-on: macos-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          xcodebuild test \
            -scheme swift-atproto-Package \
            -destination "platform=iOS Simulator,OS=17.0"
