name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build (${{ matrix.os }}, Swift ${{ matrix.swift-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]
        swift-version: ["5.9"]
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}
      - uses: actions/checkout@v3
      - name: Build
        run: make build

  test:
    name: Test (${{ matrix.os }}, Swift ${{ matrix.swift-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]
        swift-version: ["5.9"]
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift-version }}
      - uses: actions/checkout@v3
      - name: Test
        run: make test
